name: Docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Docker aapije meta
      id: aapije-meta
      uses: docker/metadata-action@v3
      with:
        images: |
          selfhoster/aapije
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Docker meta
      id: juvuln-meta
      uses: docker/metadata-action@v3
      with:
        images: |
          selfhoster/juvuln
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Docker meta
      id: malgomaj-meta
      uses: docker/metadata-action@v3
      with:
        images: |
          selfhoster/malgomaj
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}
          type=sha

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build aapije and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: build/aapije/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.aapije-meta.outputs.tags }}
        labels: ${{ steps.aapije-meta.outputs.labels }}

    - name: Update aapije repo description
      uses: peter-evans/dockerhub-description@v2
      if: github.event_name == 'push'
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: selfhoster/aapije

    - name: Build juvuln and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: build/juvuln/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.juvuln-meta.outputs.tags }}
        labels: ${{ steps.juvuln-meta.outputs.labels }}

    - name: Update juvuln repo description
      if: github.event_name == 'push'
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: selfhoster/juvuln

    - name: Build malgomaj and push to Docker Hub
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        file: build/malgomaj/Dockerfile
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.malgomaj-meta.outputs.tags }}
        labels: ${{ steps.malgomaj-meta.outputs.labels }}

    - name: Update malgomaj repo description
      if: github.event_name == 'push'
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: selfhoster/malgomaj
